package com.csis3275.blackbox;

// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.containsString;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;

public class ReservationEmail_TESTING_sli_15 {
	private WebDriver driver;
	private Map<String, Object> vars;
	JavascriptExecutor js;

	@Before
	public void setUp() {
		// Chrome Driver
		System.setProperty("webdriver.chrome.driver", "c:/temp/chromedriver.exe");
		// Scott - "c:/temp/chromedriver.exe"
		// Ricardo - "C:/Programs/ChromeDriver/chromedriver.exe"
		driver = new ChromeDriver();
		js = (JavascriptExecutor) driver;
		vars = new HashMap<String, Object>();
	}

	@After
	public void tearDown() {
		driver.quit();
	}

	  @Test
	  public void reservation() throws InterruptedException {
		  WebDriverWait waitElement = new WebDriverWait(driver, 30);
		  
	    driver.get("http://localhost:8080/");
	    driver.manage().window().setSize(new Dimension(1550, 1299));
	    driver.findElement(By.id("lmail")).click();
	    driver.findElement(By.id("lmail")).sendKeys("scott@gmail.com");
	    driver.findElement(By.id("lpassword")).sendKeys("test");
	    //driver.findElement(By.id("lmail")).sendKeys("scottlinden@me.com");
	    //driver.findElement(By.id("lpassword")).sendKeys("asdf");
	    driver.findElement(By.xpath("//button[@type=\'submit\']")).click();
	    Thread.sleep(3000); //Pause
	    driver.findElement(By.linkText("Reservations")).click();
	    driver.findElement(By.xpath("(//button[@type=\'button\'])[3]")).click();
	    driver.findElement(By.id("title")).click();
	    driver.findElement(By.id("title")).sendKeys("Test1");
	    driver.findElement(By.id("ateendees")).sendKeys("5");
	    driver.findElement(By.id("type")).click();
	    {
	      WebElement dropdown = driver.findElement(By.id("type"));
	      dropdown.findElement(By.xpath("//option[. = 'Study Group']")).click();
	    }
	    driver.findElement(By.id("type")).click();
	    driver.findElement(By.id("start")).click();
	    driver.findElement(By.id("start")).sendKeys("01-01-2021");
	    driver.findElement(By.id("start")).sendKeys(Keys.TAB);
	    driver.findElement(By.id("start")).sendKeys("09:00AM");
	    		
	    driver.findElement(By.id("end")).sendKeys("01-01-2021");
	    driver.findElement(By.id("end")).sendKeys(Keys.TAB);
	    driver.findElement(By.id("end")).sendKeys("10:00AM");
	    driver.findElement(By.id("status")).click();
	    {
	      WebElement dropdown = driver.findElement(By.id("status"));
	      dropdown.findElement(By.xpath("//option[. = 'Active']")).click();
	    }
	    driver.findElement(By.id("status")).click();
	    driver.findElement(By.id("userID")).click();
	    driver.findElement(By.id("userID")).click();
	    {
	      WebElement dropdown = driver.findElement(By.id("userID"));
	      dropdown.findElement(By.xpath("//option[. = '82']")).click();
	    }
	    driver.findElement(By.id("userID")).click();
	    driver.findElement(By.id("roomID")).click();
	    {
	      WebElement dropdown = driver.findElement(By.id("roomID"));
	      dropdown.findElement(By.xpath("//option[. = 'C304']")).click();
	    }
	    driver.findElement(By.id("roomID")).click();
	    driver.findElement(By.cssSelector(".btn")).click();
	    assertThat(driver.findElement(By.xpath("//tr[151]/td[2]")).getText(), is("Test1"));
	    assertThat(driver.findElement(By.xpath("//tr[151]/td[3]")).getText(), is("5"));
	    assertThat(driver.findElement(By.xpath("//tr[151]/td[4]")).getText(), is("Study Group"));
	    assertThat(driver.findElement(By.xpath("//tr[151]/td[7]")).getText(), is("Active"));
	    assertThat(driver.findElement(By.cssSelector(".alert")).getText(), containsString("has been added and an email reminder has been sent!"));
	    
	    driver.findElement(By.xpath("(//a[contains(text(),\'Update\')])[151]")).click();
	    waitElement.until(ExpectedConditions.elementToBeClickable(By.xpath("//input[@id=\'title\']")));
	    driver.findElement(By.xpath("//input[@id=\'title\']")).clear();
	    driver.findElement(By.xpath("//input[@id=\'title\']")).sendKeys("Test5");
	    driver.findElement(By.xpath("//input[@id=\'ateendees\']")).clear();
	    driver.findElement(By.xpath("//input[@id=\'ateendees\']")).sendKeys("50");
	    driver.findElement(By.xpath("//select[@id=\'type\']")).click();
	    {
	      WebElement dropdown = driver.findElement(By.id("type"));
	      dropdown.findElement(By.xpath("//option[. = 'Presentation']")).click();
	    }
	    driver.findElement(By.id("type")).click();
	    driver.findElement(By.xpath("//form[@id=\'reservation\']/div[3]/div[2]")).click();
	    driver.findElement(By.xpath("//form[@id=\'reservation\']/div[3]/div[3]/select")).click();
	    {
	      WebElement dropdown = driver.findElement(By.id("roomID"));
	      dropdown.findElement(By.xpath("//option[. = 'T404']")).click();
	    }
	    driver.findElement(By.xpath("//form[@id=\'reservation\']/div[4]/div[2]/button")).click();
	    assertThat(driver.findElement(By.xpath("//td[contains(.,\'Test5\')]")).getText(), is("Test5"));
	    assertThat(driver.findElement(By.xpath("//tr[151]/td[3]")).getText(), is("50"));
	    assertThat(driver.findElement(By.xpath("//td[contains(.,\'Presentation\')]")).getText(), is("Presentation"));
	    driver.findElement(By.xpath("//tr[151]/td[11]/a")).click();
	    assertThat(driver.findElement(By.xpath("//tr[150]/td[2]")).getText(), is(not("Test5")));
	    assertThat(driver.findElement(By.cssSelector(".alert")).getText(), containsString("has been deleted!"));
	    
	  }
	}
