package com.csis3275.blackbox;

// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.containsString;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.MatcherAssert.assertThat;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.util.concurrent.TimeUnit;
import java.net.MalformedURLException;
import java.net.URL;

public class RoomMGMT_TESTING_sli_15 {
	private WebDriver driver;
	private Map<String, Object> vars;
	JavascriptExecutor js;

	@Before
	public void setUp() {

		// Chrome Driver
		System.setProperty("webdriver.chrome.driver", "c:/temp/chromedriver.exe");
		// Scott - "c:/temp/chromedriver.exe"
		// Ricardo - "C:/Programs/ChromeDriver/chromedriver.exe"

		driver = new ChromeDriver();
		js = (JavascriptExecutor) driver;
		vars = new HashMap<String, Object>();
		// Implicitwait (time to wait after each page load)
		driver.manage().timeouts().implicitlyWait(2, TimeUnit.SECONDS);
	}
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void addRoomTESTINGsli15() {
    driver.get("http://localhost:8080/");
    driver.manage().window().setSize(new Dimension(1550, 1299));
    driver.findElement(By.xpath("//form[@id=\'login\']/div/input")).click();
    driver.findElement(By.id("lmail")).sendKeys("scottlinden@me.com");
    driver.findElement(By.id("lpassword")).sendKeys("asdf");
    driver.findElement(By.xpath("//form[@id=\'login\']/button")).click();
    driver.findElement(By.xpath("(//a[contains(@href, \'/RoomMGMT/showAllRooms\')])[2]")).click();
    driver.findElement(By.xpath("(//input[@id=\'number\'])[3]")).click();
    driver.findElement(By.xpath("(//input[@id=\'number\'])[3]")).sendKeys("Test1");
    driver.findElement(By.xpath("(//input[@id=\'floor\'])[3]")).sendKeys("1");
    driver.findElement(By.xpath("(//input[@id=\'building\'])[3]")).sendKeys("Tower");
    driver.findElement(By.xpath("(//input[@id=\'capacity\'])[3]")).sendKeys("25");
    driver.findElement(By.xpath("(//select[@id=\'roomType\'])[3]")).click();
    driver.findElement(By.xpath("(//select[@id=\'roomType\'])[3]")).click();
    driver.findElement(By.xpath("(//select[@id=\'baseCalendar\'])[3]")).click();
    driver.findElement(By.xpath("(//select[@id=\'baseCalendar\'])[3]")).click();
    driver.findElement(By.xpath("(//button[@value=\'Submit\'])[3]")).click();
    assertThat(driver.findElement(By.xpath("//td[contains(.,\'Test1\')]")).getText(), is("Test1"));
    assertThat(driver.findElement(By.xpath("//tr[72]/td[3]")).getText(), is("1"));
    assertThat(driver.findElement(By.xpath("//tr[72]/td[4]")).getText(), is("Tower"));
    assertThat(driver.findElement(By.xpath("//tr[72]/td[5]")).getText(), is("25"));
    assertThat(driver.findElement(By.xpath("//td[contains(.,\'classroom\')]")).getText(), is("classroom"));
    assertThat(driver.findElement(By.xpath("//tr[72]/td[7]")).getText(), is("1"));
    driver.findElement(By.xpath("(//a[contains(text(),\'Update\')])[72]")).click();
    driver.findElement(By.xpath("//input[@id=\'number\']")).clear();
    driver.findElement(By.xpath("//input[@id=\'number\']")).sendKeys("Test2");
    driver.findElement(By.xpath("//div/div[2]/div")).click();
    driver.findElement(By.xpath("//select[@id=\'roomType\']")).click();
    {
      WebElement dropdown = driver.findElement(By.id("roomType"));
      dropdown.findElement(By.xpath("//option[. = 'Office']")).click();
    }
    driver.findElement(By.xpath("//select[@id=\'roomType\']")).click();
    driver.findElement(By.xpath("//form[@id=\'room\']/div[3]/div[2]/button")).click();
    assertThat(driver.findElement(By.xpath("//tr[72]/td[2]")).getText(), is("Test2"));
    assertThat(driver.findElement(By.xpath("//tr[72]/td[6]")).getText(), is("Office"));
    driver.findElement(By.xpath("(//a[contains(text(),\'Delete\')])[72]")).click();
    assertThat(driver.findElement(By.xpath("//tr[71]/td[2]")).getText(), is(not("Test2")));
  }
}
